### ISSUE TITLE
Publish releases and add tags to ESPHome microWakeWord models in this repo on GitHub?

### ISSUE THREAD

**Issue by Hedda** [esphome/micro-wake-word-models#13]
Do you plan to publish releases and add tags to ESPHome microWakeWord (mWW) models from this GitHub repository as well?

- https://github.com/esphome/micro-wake-word-models/releases

- https://github.com/esphome/micro-wake-word-models/tags

@kahrendt For reference, spotted that mww ref in `home-assistant-voice.yaml` from [home-assistant-voice-pe](https://github.com/esphome/home-assistant-voice-pe) currently points your repo:

https://github.com/esphome/home-assistant-voice-pe/blob/dev/home-assistant-voice.yaml#L1483

Will you change `home-assistant-voice.yaml` in [home-assistant-voice-pe](https://github.com/esphome/home-assistant-voice-pe) to instead point to esphome's [micro-wake-word-models](https://github.com/esphome/micro-wake-word-models)?

```
micro_wake_word:
  id: mww
  models:
    - model: okay_nabu
      id: okay_nabu
    - model: hey_jarvis
      id: hey_jarvis
    - model: hey_mycroft
      id: hey_mycroft
    - model: https://github.com/kahrendt/microWakeWord/releases/download/stop/stop.json
      id: stop
      internal: true
```

- https://github.com/kahrendt/microWakeWord/releases

- https://github.com/kahrendt/microWakeWord/tags
